apiVersion: v1
kind: Namespace
metadata:
  name: alert-manager

---
apiVersion: v1
kind: Secret
metadata:
  name: alert-manager-secret
  namespace: alert-manager
type: Opaque
data:
  slack-token: eG94Yi03MzA0MjAyMTAwMDAwLTcyODIxMzA2OTQxOTQtaXpoYmhiNkV0NjNydmljQUJWVXpkeW9H

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-manager-config
  namespace: alert-manager
data:
  PORT: "5000"
  DEBUG: "False"
  PROMETHEUS_URL: "http://prometheus-service.monitoring.svc.cluster.local:9090"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-manager
  namespace: alert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-manager
  template:
    metadata:
      labels:
        app: alert-manager
    spec:
      containers:
      - name: alert-manager
        image: 96213/alert-manager:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: alert-manager-config
              key: PORT
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: alert-manager-config
              key: DEBUG
        - name: PROMETHEUS_URL
          valueFrom:
            configMapKeyRef:
              name: alert-manager-config
              key: PROMETHEUS_URL
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: alert-manager-secret
              key: slack-token
---
apiVersion: v1
kind: Service
metadata:
  name: alert-manager
  namespace: alert-manager
spec:
  selector:
    app: alert-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
