apiVersion: v1
kind: Secret
metadata:
  name: alert-manager-secret
  namespace: alert-manager
type: Opaque
data:
  slack-token: eG94Yi03MzA0MjAyMTAwMDAwLTcyODIxMzA2OTQxOTQtaXpoYmhiNkV0NjNydmljQUJWVXpkeW9H
